### ISSUE TITLE
Unexpected exception 'java.lang.IllegalArgumentException'

### ISSUE THREAD

**Issue by ep-mark** [BowlerHatLLC/vscode-as3mxml#287]
When I run the Actionscript & MXML Language server it shows the following error:
Unexpected exception 'java.lang.IllegalArgumentException'

How would I go about tracking down what is causing this problem? It is a big project and I have no idea where to start.

**Comment by joshtynjala** [comment]
This indicates a bug in the extension. Please copy and paste the complete call stack that accompanies the java.lang.IllegalArgumentException. That will give me a clue about what could be wrong.

**Comment by ep-mark** [comment]
Sorry, I am not sure where to copy and paste the complete call stack.
![image](https://user-images.githubusercontent.com/20032631/46698471-ae289280-cc73-11e8-95ab-f5c16988a76c.png)

**Comment by joshtynjala** [comment]
Oh I see, it's coming up as a compiler error. That was not what I was expecting. This could be very difficult to debug.

If you right-click on the error, you should see a **Copy** option. Please copy it and paste the contents here. The data that you paste will look like a JSON file. Hopefully, this will contain the call stack for the Java error.

**Comment by ep-mark** [comment]
Here is goes:
{
	"resource": "/c:/wf/LP/flash/ControlPanel/",
	"owner": "_generated_diagnostic_collection_name_#5",
	"code": "1530",
	"severity": 8,
	"message": "Unexpected exception 'java.lang.IllegalArgumentException'.",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}

**Comment by joshtynjala** [comment]
Hmmm... that's unfortunate.

Can you switch to the **Output** view, select **ActionScript & MXML language server** from the drop down, and check if there are any errors printed there? If you find anything, please copy/paste it here too. Thanks!

**Comment by ep-mark** [comment]
I can't actually see **ActionScript & MXML language server** in the **Output** view.

![image](https://user-images.githubusercontent.com/20032631/46700035-36109b80-cc78-11e8-9fea-7eb70a7873a1.png)

Do I need to be debugigng the extension for this to be shown?

**Comment by joshtynjala** [comment]
No, it just means that the language server didn't catch any errors in its own code, so it hasn't output anything.

Based on this information, I can conclude that this error is happening entirely inside the Apache Royale compiler, so there's definitely a bug there.

(Note: Even if you aren't building an Apache Royale app, its compiler is always used by the language server to provide code intelligence because it's very flexible and will work with projects built with other ActionScript SDKs).

One interesting thing I see is that the error is being presented for a folder rather than an *.as* or *.mxml* file:

```
"resource": "/c:/wf/LP/flash/ControlPanel/",
```

This seems a bit strange to me. Can you share the contents your *asconfig.json* file? Maybe there's some field in your *asconfig.json* file that is referencing this folder incorrectly.

**Comment by ep-mark** [comment]
I debugged the extension and now see the output

```
Oct 10, 2018 10:45:25 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
  "jsonrpc": "2.0",
  "method": "initialized",
  "params": {}
}
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
	at java.util.HashMap$KeyIterator.next(HashMap.java:1461)
	at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5594)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5615)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.getCompilationUnit(ActionScriptTextDocumentService.java:5711)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.checkFilePathForAllProblems(ActionScriptTextDocumentService.java:6018)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.checkFilePathForProblems(ActionScriptTextDocumentService.java:5991)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.checkFilePathForProblems(ActionScriptTextDocumentService.java:5977)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.checkProjectForProblems(ActionScriptTextDocumentService.java:5916)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.setInitialized(ActionScriptTextDocumentService.java:2273)
	at com.as3mxml.vscode.ActionScriptLanguageServer.initialized(ActionScriptLanguageServer.java:174)
	... 16 more


```

**Comment by ep-mark** [comment]
asconfig.json
`
{
	"config": "flex",
	"compilerOptions": {
		"output": "bin/ControlPanel.swf",
		"load-config": [
			"src/config_raw.xml"
		]
	},
	"files": [
		"src/ControlPanel.mxml"
	]
}
`

**Comment by joshtynjala** [comment]
I'll also need to see the contents of *config_raw.xml*.

**Comment by ep-mark** [comment]
Here is the config_raw.xml
[config_raw.zip](https://github.com/BowlerHatLLC/vscode-nextgenas/files/2462360/config_raw.zip)

**Comment by joshtynjala** [comment]
In *config_raw.xml*, I see a lot of relative paths that reference parent directories.

* ../../node_modules/flex-sdk/
* ../libs
* ../src
* ../../Common_libs/includes

Assuming that you generated this file from Flash Builder or somewhere else, can you verify that these are all correct paths based on the location of your VSCode project?

**Comment by ep-mark** [comment]
These paths are all correct. The project builds ok when I use flexSdk.bin.mxmlc using config_raw.xml.

Should I try and compile using Apache Royale?

**Comment by joshtynjala** [comment]
No, you shouldn't try to compile a SWF with Apache Royale. You don't want to deal with all of that.

I'm sorry, but I don't have a good suggestion for you. Maybe it would be smart to start with an empty project and then slowly introduce parts of your app (including the custom compiler options, as you start actually need them). You might have more luck getting things to work, or at least narrow down exactly what is breaking by doing it that way.

**Comment by ep-mark** [comment]
Thanks. I will give that a try. I will let you know how I get on!
