### ISSUE TITLE
Extension randomly crashes on hovering a symbol ("Request textDocument/hover failed")

### ISSUE THREAD

**Issue by olafkrueger** [BowlerHatLLC/vscode-as3mxml#304]
Hi,
from time to time the extension crashes  when I hover with pressed control key over a symbol [1].
I can continue coding, but e.g. Goto and code completion gets unresponsive so I have to restart the Actionscript/MXML server.
Unfortunately, I can't reproduce this issue on demand. It seems to me that it happens randomly... not sure... I have to observe this a bit more. I would say I never ran into this with v0.14.0.

I am using Flex with AIR on Windows7 here,

Thanks!
Olaf

[1]
```
[Error - 12:58:20 PM] Request textDocument/hover failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2214)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4053)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4992)
	at org.apache.royale.compiler.internal.projects.CompilerProject.getCacheForScope(CompilerProject.java:676)
	at org.apache.royale.compiler.internal.definitions.InterfaceDefinition.resolveExtendedInterfaces(InterfaceDefinition.java:122)
	at org.apache.royale.compiler.internal.definitions.TypeDefinitionBase$TypeIterator.pushChildren(TypeDefinitionBase.java:290)
	at org.apache.royale.compiler.internal.definitions.TypeDefinitionBase$TypeIterator.next(TypeDefinitionBase.java:217)
	at org.apache.royale.compiler.internal.definitions.TypeDefinitionBase$TypeIterator.next(TypeDefinitionBase.java:175)
	at org.apache.royale.compiler.internal.scopes.TypeScope.getPropertyForScopeChain(TypeScope.java:262)
	at org.apache.royale.compiler.internal.scopes.ScopeView.getPropertyForScopeChain(ScopeView.java:72)
	at org.apache.royale.compiler.internal.scopes.ASScope.findProperty(ASScope.java:1119)
	at org.apache.royale.compiler.internal.scopes.ASScope.findProperty(ASScope.java:1061)
	at org.apache.royale.compiler.internal.scopes.ASScope.findProperty(ASScope.java:1277)
	at org.apache.royale.compiler.internal.scopes.ASScope.findProperty(ASScope.java:999)
	at org.apache.royale.compiler.internal.scopes.ASScopeCache.findProperty(ASScopeCache.java:153)
	at org.apache.royale.compiler.internal.scopes.ASScope.findProperty(ASScope.java:1428)
	at org.apache.royale.compiler.internal.tree.as.IdentifierNode.resolve(IdentifierNode.java:394)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.actionScriptHoverWithNode(ActionScriptTextDocumentService.java:3389)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.actionScriptHover(ActionScriptTextDocumentService.java:3370)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.lambda$hover$1(ActionScriptTextDocumentService.java:526)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	... 5 more
Caused by: java.lang.NullPointerException
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4052)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:4057)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4986)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4992)
	at org.apache.royale.compiler.internal.scopes.ASProjectScope.addScopeToCompilationUnitScopeList(ASProjectScope.java:1310)
	at org.apache.royale.compiler.internal.projects.CompilerProject$ScopeCacheLoader.load(CompilerProject.java:107)
	at org.apache.royale.compiler.internal.projects.CompilerProject$ScopeCacheLoader.load(CompilerProject.java:96)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3628)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2336)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2295)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2208)
	... 27 more
```

**Comment by joshtynjala** [comment]
Unfortunately, it will probably be difficult to fix until we figure out some steps to reproduce.

These errors in `com.google.common.cache.LocalCache` are usually related to multiple threads updating the compiler's state at the same time. I thought that I forced all requests to wait until the compiler is idle, but perhaps I've missed one somewhere.

**Comment by joshtynjala** [comment]
> Is there a chance that errors like this go away with the next as3mxml version which will probably includes your latest Apache Royale compiler improvements?

I don't think so. I'm pretty sure that this is a bug in the extension.

**Comment by olafkrueger** [comment]
@joshtynjala 
Piotr has pointed me out that I accidently forgot to add needded sources to the source-path in some cases. Since anything is configured properly I never ran into this issue anymore.
Unbelievable that I didn't notcice this...
However, it seems to me that this resolves this issue.

Sorry for the noise! ;-)

See also #253

**Comment by piotrzarzycki21** [comment]
For the sake of completeness of whole situation. If we don't have need of place anything in the source-path - there is absolutely no problem with code completion and all features. 
However if we add for example some source path from library which we are using and forgot to add path to our own source - we run into all of that issue. - Not sure if it's actually, a bug - if not maybe documentation should mention about that.

**Comment by olafkrueger** [comment]
Hmmm... it seems I was a bit too optimistic.
I just ran into this issue again,  I'll observe it furthermore.

**Comment by joshtynjala** [comment]
Earlier today, I committed a fix for a potential multi-threading conflict. The fix will be included in the upcoming v0.16. If we're lucky, your issue may be fixed after the update.

**Comment by olafkrueger** [comment]
I am using v0.16.0 now and will observe if the issue is fixed.
Thank you so much for the new release!

**Comment by olafkrueger** [comment]
After one day of working with v0.16.0 I never run into this, just into #253.
But it seems to me that the extension crashes silently (without throwing any errors) in very rare cases.
Not totally sure, will continue observing ;-)
