### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/vscode-as3mxml#332]
> This is what I'm getting having Win Antivirus ON [1]. Once it's occurs usage of extension is pointless. Everything is freezing, any rollover on component or as3 mxml is causing output in console.
> https://paste.apache.org/nBnH

See also: prominic/Moonshine-IDE#330

**Comment by joshtynjala** [comment]
@piotrzarzycki21 When the ConcurrentModificationException is thrown, is hover() always in the call stack? Or does it get thrown from somewhere else the first time?

at com.as3mxml.vscode.ActionScriptTextDocumentService.lambda$hover$1(ActionScriptTextDocumentService.java:514)

If it gets thrown somewhere else the first time, can you share that particular call stack with me? I think that it may be triggered by something else, and then once it has happened the first, other parts of the code are simply more likely to be affected too.

Additionally, can you try to remember what you were doing when it happened? For instance, had you just created any new files? Or did you do anything else that might affect the file system?

Thanks!

**Comment by piotrzarzycki21** [comment]
> If it gets thrown somewhere else the first time, can you share that particular call stack with me?

This is call stack right after when it occurs - I haven't done anything more after that:

```
SEVERE: Internal error: java.util.ConcurrentModificationException
: java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
: 	at java.base/java.lang.Thread.run(Thread.java:834)
: Caused by: java.util.ConcurrentModificationException
: 	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
: 	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.cleanupInvisibleUnits(ActionScriptTextDocumentService.java:2727)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getProject(ActionScriptTextDocumentService.java:6170)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.textDocumentUriToProject(ActionScriptTextDocumentService.java:827)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.textDocumentIdentifierToProject(ActionScriptTextDocumentService.java:804)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.textDocumentPositionParamsToProject(ActionScriptTextDocumentService.java:799)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.lambda$hover$1(ActionScriptTextDocumentService.java:514)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
: 	... 4 more
: 
: Feb 26, 2019 12:41:00 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
: SEVERE: Internal error: java.util.ConcurrentModificationException
: java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
: 	at java.base/java.lang.Thread.run(Thread.java:834)
: Caused by: java.util.ConcurrentModificationException
: 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
: 	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
: 	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1045)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5953)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5974)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getCompilationUnit(ActionScriptTextDocumentService.java:6114)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getAST(ActionScriptTextDocumentService.java:6020)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6698)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6681)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6643)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.actionScriptHover(ActionScriptTextDocumentService.java:3563)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.lambda$hover$1(ActionScriptTextDocumentService.java:547)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
: 	... 4 more
: 
: Feb 26, 2019 12:41:00 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
: SEVERE: Internal error: java.util.ConcurrentModificationException
: java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
: 	at java.base/java.lang.Thread.run(Thread.java:834)
: Caused by: java.util.ConcurrentModificationException
: 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
: 	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
: 	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1045)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5953)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5974)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getCompilationUnit(ActionScriptTextDocumentService.java:6114)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getAST(ActionScriptTextDocumentService.java:6020)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6698)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6681)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6643)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.actionScriptHover(ActionScriptTextDocumentService.java:3563)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.lambda$hover$1(ActionScriptTextDocumentService.java:547)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
: 	... 4 more
: 
: Feb 26, 2019 12:40:59 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
: SEVERE: Internal error: java.util.ConcurrentModificationException
: java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
: 	at java.base/java.lang.Thread.run(Thread.java:834)
: Caused by: java.util.ConcurrentModificationException
: 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
: 	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
: 	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1045)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5953)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5974)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getCompilationUnit(ActionScriptTextDocumentService.java:6114)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getAST(ActionScriptTextDocumentService.java:6020)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6698)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6681)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6643)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.actionScriptHover(ActionScriptTextDocumentService.java:3563)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.lambda$hover$1(ActionScriptTextDocumentService.java:547)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
: 	... 4 more
: 
: Feb 26, 2019 12:40:59 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
: SEVERE: Internal error: java.util.ConcurrentModificationException
: java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
: 	at java.base/java.lang.Thread.run(Thread.java:834)
: Caused by: java.util.ConcurrentModificationException
: 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
: 	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
: 	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1045)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5953)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5974)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getCompilationUnit(ActionScriptTextDocumentService.java:6114)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getAST(ActionScriptTextDocumentService.java:6020)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6698)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6681)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6643)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.actionScriptHover(ActionScriptTextDocumentService.java:3563)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.lambda$hover$1(ActionScriptTextDocumentService.java:547)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
: 	... 4 more
: 
: Feb 26, 2019 12:40:59 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
: SEVERE: Internal error: java.util.ConcurrentModificationException
: java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
: 	at java.base/java.lang.Thread.run(Thread.java:834)
: Caused by: java.util.ConcurrentModificationException
: 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
: 	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
: 	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1045)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5953)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5974)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getCompilationUnit(ActionScriptTextDocumentService.java:6114)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getAST(ActionScriptTextDocumentService.java:6020)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6698)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6681)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6643)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.actionScriptHover(ActionScriptTextDocumentService.java:3563)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.lambda$hover$1(ActionScriptTextDocumentService.java:547)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
: 	... 4 more
: 
```

**Comment by piotrzarzycki21** [comment]
> Additionally, can you try to remember what you were doing when it happens? For instance, had you just created any new files? Or did you do anything else that might affect the file system?

I have recorded gif for you, it's pretty long and I'm writing some random code. ;) I don't do anything specific than usually to trigger that issue. It is newest [dev build](https://moonshine-ide.com/downloads/releases/dev/windows/) with OpenJDK 11.0.2
Note two additional issues:
1. I was waiting pretty long for first code completion list show. I can live with that part cause it's working fast later on :)
2. Auto closing doesn't work anymore. When I type `<j:Group>` and later `</j:Group>` - It doesn't show up in code completion. 

![issue_moonshine](https://user-images.githubusercontent.com/24554795/53411265-568e8780-39c6-11e9-8c90-ea97d0dd26cb.gif)

**Comment by joshtynjala** [comment]
> Auto closing doesn't work anymore. When I type <j:Group> and later </j:Group> - It doesn't show up in code completion.

This has never worked consistently. It's only in certain contexts. I could not figure out how to make it work everywhere.

**Comment by piotrzarzycki21** [comment]
@joshtynjala One additional question maybe a bit off topic. If I set JAVA path in Moonshine - does it actually mean that language server will use it ?

**Comment by piotrzarzycki21** [comment]
> @joshtynjala One additional question maybe a bit off topic. If I set JAVA path in Moonshine - does it actually mean that language server will use it ?

I have answered to that question myself. Sorry for off topic. It looks like we have something wrong in Moonshine. I have uninstalled Java JDK and left only with OpenJDK - Moonshine is asking for JDK of every start. I will raise issue in Moonshine github to investigate. VSCode is working fine with OpenJDK.

**Comment by joshtynjala** [comment]
Screenshot from the video with a slightly different stack trace than the one linked at Apache Paste Bucket:

![video-stack-exception](https://user-images.githubusercontent.com/141885/53439559-21c70400-39b7-11e9-8636-33f4ba1a2cb4.png)

**Comment by joshtynjala** [comment]
Oh wait, I see that was included in your post above. Just to make it easier for me to find the different variations, I'm going to add them separately here:

```
SEVERE: Internal error: java.util.ConcurrentModificationException
: java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
: 	at java.base/java.lang.Thread.run(Thread.java:834)
: Caused by: java.util.ConcurrentModificationException
: 	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1042)
: 	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:996)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.cleanupInvisibleUnits(ActionScriptTextDocumentService.java:2727)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getProject(ActionScriptTextDocumentService.java:6170)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.textDocumentUriToProject(ActionScriptTextDocumentService.java:827)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.textDocumentIdentifierToProject(ActionScriptTextDocumentService.java:804)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.textDocumentPositionParamsToProject(ActionScriptTextDocumentService.java:799)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.lambda$hover$1(ActionScriptTextDocumentService.java:514)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
: 	... 4 more
```

```
: SEVERE: Internal error: java.util.ConcurrentModificationException
: java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
: 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
: 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
: 	at java.base/java.lang.Thread.run(Thread.java:834)
: Caused by: java.util.ConcurrentModificationException
: 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1493)
: 	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1516)
: 	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1045)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5953)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.findCompilationUnit(ActionScriptTextDocumentService.java:5974)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getCompilationUnit(ActionScriptTextDocumentService.java:6114)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getAST(ActionScriptTextDocumentService.java:6020)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6698)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6681)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.getOffsetNode(ActionScriptTextDocumentService.java:6643)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.actionScriptHover(ActionScriptTextDocumentService.java:3563)
: 	at com.as3mxml.vscode.ActionScriptTextDocumentService.lambda$hover$1(ActionScriptTextDocumentService.java:547)
: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
: 	... 4 more
```

**Comment by joshtynjala** [comment]
Unfortunately, I still can't figure out how to reproduce this issue on one of my computers. However, I made some tweaks related to thread-safety that may help. These fixes will be in the upcoming vscode-as3mxml v0.18.

**Comment by piotrzarzycki21** [comment]
My factors to that issue are always:
1) Moonshine is installed - I'm not sure whether I was able to reproduce issue with running IDE in debugging mode 
2) Have switched On Real-time protection in Windows 
Maybe my PC is a lot slower than yours and this is also additional factor which causes that issue.

**Comment by joshtynjala** [comment]
> Have switched On Real-time protection in Windows. Maybe my PC is a lot slower than yours and this is also additional factor which causes that issue.

That's what I'm thinking. I have real time protection enabled, but I have a pretty new computer, so it may be faster than yours.

My main hard drive is an SSD, and I also tried an external

**Comment by joshtynjala** [comment]
I'm going to close this issue now that I've released the new v0.18 update. If it pops up again, I can re-open and continue my investigation.

Moonshine has not been updated with the new language server yet, but I'll probably do that next week.

**Comment by piotrzarzycki21** [comment]
Thanks Josh! I will wait for that update. However @olafkrueger if you could observer as well whether you have any kind of exception like that, cause I know that you have switched to VSCode completely.

**Comment by olafkrueger** [comment]
> However @olafkrueger if you could observer as well whether you have any kind of exception like that

Until now it never occured here that VSCode freezes completely.
However, I will observe the exceptions!

**Comment by piotrzarzycki21** [comment]
@joshtynjala I don't have good news for you. It looks like I don't get anymore error on the console, but language server is switching OFF after couple of minutes of work when I have real-time protection enabled. Everything is working fine when it's OFF. I don't get anything in console when it is happen. I have in Moonshine's problems view only information:

`A fatal error occurred. Error checking has been disabled, except for simple syntax problems.`

Once I get that I have to restart Moonshine to get up code completion again.

**Comment by joshtynjala** [comment]
Okay, thanks Piotr!
