### ISSUE TITLE
ActionScript Release Task: Task generates java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-as3mxml#341]
Hello Josh,

I have an issue when trying to build a release via the `"ActionScript: compile release - asconfig.json"` task. Everything works fine with debug builds.

Here is the error I get during the build:
```
> Executing task: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe -jar c:\Users\Adolio\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.18.0\bin\asconfigc.jar --sdk c:\AIR\AIR_SDK_32_0 --debug=false --project e:\Development\Air\Starling-Sandbox\asconfig.json <

Loading configuration: c:\AIR\AIR_SDK_32_0\frameworks\air-config.xml

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.io.ByteArrayOutputStream.grow(Unknown Source)
        at java.io.ByteArrayOutputStream.ensureCapacity(Unknown Source)
        at java.io.ByteArrayOutputStream.write(Unknown Source)
        at SevenZip.Compression.RangeCoder.Encoder.ShiftLow(Encoder.java:60)
        at SevenZip.Compression.RangeCoder.Encoder.EncodeDirectBits(Encoder.java:80)
        at SevenZip.Compression.LZMA.Encoder.CodeOneBlock(Encoder.java:1188)
        at SevenZip.Compression.LZMA.Encoder.Code(Encoder.java:1284)
        at com.adobe.flash.swf.io.LZMACompressor.compress(LZMACompressor.java:138)
        at com.adobe.flash.swf.io.SWFWriter.writeTo(SWFWriter.java:2695)
        at com.adobe.flash.swf.io.SWFWriter.writeTo(SWFWriter.java:2762)
        at com.adobe.flash.compiler.clients.MXMLC.writeSWF(MXMLC.java:807)
        at com.adobe.flash.compiler.clients.MXMLC.compile(MXMLC.java:564)
        at com.adobe.flash.compiler.clients.MXMLC.mainNoExit(MXMLC.java:242)
        at com.adobe.flash.compiler.clients.MXMLC.mainNoExit(MXMLC.java:196)
        at com.adobe.flash.compiler.clients.MXMLC.staticMainNoExit(MXMLC.java:167)
        at com.adobe.flash.compiler.clients.MXMLC.main(MXMLC.java:144)
The terminal process terminated with exit code: 1
```

Best,
Aurélien

**Comment by joshtynjala** [comment]
I updated the code that executes the compiler to set Java's max heap size to the same values that the command line compilers use. Previously, I was not setting the max heap size at all, so it used some kind of default. Hopefully, that should do the trick.

**Comment by Adolio** [comment]
Thanks Josh for the fix. I will keep you updated as soon as the next version of vscode-nextgenas will be available. I'm just surprised to reach Java's default max heap size because the project on which I'm using vscode-nextgenas is pretty small for now.

**Comment by neminovno** [comment]
> 
> 
> I updated the code that executes the compiler to set Java's max heap size to the same values that the command line compilers use. Previously, I was not setting the max heap size at all, so it used some kind of default. Hopefully, that should do the trick.

@joshtynjala Could it be that setting max heap size https://github.com/BowlerHatLLC/vscode-as3mxml/blob/8c89f1a059d25c217eedfe75a4f7fa2b8a5839c4/asconfigc/src/main/java/com/as3mxml/asconfigc/compiler/DefaultCompiler.java#L61 potentially slows done compilation?
How to set custom Java VM -Xmx value?

**Comment by joshtynjala** [comment]
You may be able to set a custom value using additionalOptions. I don't know for sure if it will work, though.

**Comment by joshtynjala** [comment]
It's guess that it's possible that the extra check that I added to avoid errors when overwriting read-only files with copySourcePathAssets it's making the copying phase slower. Previously, it was just copying them all immediately, but now it checks the read only status first. I'll try to do some tests to see which of these two changes is the culprit.

**Comment by joshtynjala** [comment]
@neminovno I have confirmed that the extra check for read-only files made `copySourcePathAssets` significantly slower. In a very large project that I work on, copying files went from about 3 seconds to 22 seconds!

I suspect that this is the cause of the slowdown that you also observed. It will be fixed in the next update.

**Comment by neminovno** [comment]
@joshtynjala Great. Thanks. I will test it after next update.

**Comment by joshtynjala** [comment]
FYI: In today's update, VSCode no longer sets `-Xmx512m` automatically when compiling. This may cause the out of memory error to return. However, you can now pass custom arguments to the Java Virtual Machine when compiling. In your VSCode settings, add the following value to restore the previous behavior:

```json
{
	"as3mxml.asconfigc.jvmargs": "-Xmx512m"
}
```
