### ISSUE TITLE
Can not resolve config constant / Access of undefined property

### ISSUE THREAD

**Issue by jnpatrick99** [BowlerHatLLC/vscode-as3mxml#363]
Hi! I finally got project alive and working in VS Code. Yay! Thank you for the all hard work! This is extension is really cool!

The last problem I have is with compiler definitions. When I define them like this:

```
"define":
[
    {
    "name": "CONFIG::funcName",
    "value": "'functionName'"
 }
]
```
Then I receive the `Can not resolve config constant 'funcName'` error when I use CONFIG::funcName in the code. My code looks like `someClass.someMethod( CONFIG::funcName )`.
When I define it as 
````
"additionalOptions": "-define=CONFIG::funcName,'functionName'"
````
I receive a lot of crashes like
````
	at org.apache.royale.compiler.internal.definitions.AmbiguousDefinition.resolveAmbiguities(AmbiguousDefinition.java:130)
	at org.apache.royale.compiler.internal.scopes.ASScopeCache.findProperty(ASScopeCache.java:167)
	at org.apache.royale.compiler.internal.scopes.ASScope.findProperty(ASScope.java:1428)
	at org.apache.royale.compiler.internal.definitions.references.LexicalReference.resolve(LexicalReference.java:72)
	at org.apache.royale.compiler.internal.definitions.DefinitionBase.resolveType(DefinitionBase.java:1062)
	at org.apache.royale.compiler.internal.definitions.DefinitionBase.resolveType(DefinitionBase.java:1102)
	at org.apache.royale.compiler.internal.definitions.DefinitionBase.resolveType(DefinitionBase.java:884)
	at org.apache.royale.compiler.internal.definitions.AmbiguousDefinition.resolveAmbiguousVariableDefinitions(AmbiguousDefinition.java:208)
````
and then `Access of possibly undefined property 'CONFIG'` error.

What do you think can be the source of these problems?

**Comment by joshtynjala** [comment]
I just gave this one a try, and it is working successfully for me:

```
"define":
[
    {
    "name": "CONFIG::funcName",
    "value": "'functionName'"
 }
]
```

Do you have multiple projects? Maybe one or more libraries that are dependencies of the app? If that's the case, it might be that you need to define the constant separately for each project.

I tried this one too, and I ran into some issues:

```
"additionalOptions": "-define=CONFIG::funcName,'functionName'"
```

It wasn't giving me the crashes, but the compiler gave me these errors when I tried to build:

> Error: The initializer for a configuration value must be a compile time constant.
> Error: Can not resolve config constant: 'funcName'

I determined that this is because strings must be double quoted in config constants. This should work better:

```
"additionalOptions": "-define+=CONFIG::funcName,\"'functionName'\""
```

Notice that it has double quotes on the outside and single quotes on the inside, just like how you defined the constant in `compilerOptions` with two sets of quotes. It's quirky, but that's what the compiler wants. The reason for this is because just the double quotes is parsed as an expression that gets evaluated at a compile time. For example, the compiler would allow you to use the expression "1 + 2" for a constant.

**Comment by jnpatrick99** [comment]
Wow, thank you very much for the detailed answer! I'll try it out!

**Comment by jnpatrick99** [comment]
Unfortunately I'm still receiving a crash :( Please find attached the sample project (only two files) which 100% produces the following crash on my end. (I'm probably having some sort of asconfig.json misconfiguration, but I can't find what's wrong. The project is really just what I showed above)

[crash.zip](https://github.com/BowlerHatLLC/vscode-as3mxml/files/3184434/crash.zip)

```
May 15, 2019 2:02:51 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint$$Lambda$7/1146848448.apply(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 12 more
Caused by: java.lang.NullPointerException
	at org.apache.royale.compiler.config.Configurator.getConfigurationProblems(Configurator.java:445)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.getProject(ActionScriptTextDocumentService.java:6060)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.checkProjectForProblems(ActionScriptTextDocumentService.java:6119)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.addWorkspaceFolder(ActionScriptTextDocumentService.java:356)
	at com.as3mxml.vscode.ActionScriptLanguageServer.initialize(ActionScriptLanguageServer.java:105)
	... 17 more

[Error - 2:02:51 PM] Server initialization failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint$$Lambda$7/1146848448.apply(Unknown Source)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 12 more
Caused by: java.lang.NullPointerException
	at org.apache.royale.compiler.config.Configurator.getConfigurationProblems(Configurator.java:445)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.getProject(ActionScriptTextDocumentService.java:6060)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.checkProjectForProblems(ActionScriptTextDocumentService.java:6119)
	at com.as3mxml.vscode.ActionScriptTextDocumentService.addWorkspaceFolder(ActionScriptTextDocumentService.java:356)
	at com.as3mxml.vscode.ActionScriptLanguageServer.initialize(ActionScriptLanguageServer.java:105)
	... 17 more

```

**Comment by joshtynjala** [comment]
I am able to reproduce the NullPointerException when you add `define` to `additionalOptions`.

However, when I add `define` in `compilerOptions` instead, this works correctly for me:

```json5
{
	"type": "lib",
	"config": "air",
	"compilerOptions": {
		"warnings": false,
		"output": "bin/something.swc",
		"target-player": "10.1",
		"source-path": [
			"src"
		],
		"library-path": [
		],
		"include-sources": [
			"src"
		],
		"define": [
			{
				"name": "CONFIG::funcName",
				"value": "'functionName'"
			}
		]
	}
}
```

**Comment by joshtynjala** [comment]
I added an additional check to prevent the crash, if something similar pops up in the future. I also fixed the bug that caused the crash when parsing `additionalOptions`.

**Comment by jnpatrick99** [comment]
Thank you very much! Seems to be working fine now!
