### ISSUE TITLE
Can't Open a Socket for Runnning Language Server

### ISSUE THREAD

**Issue by yishayw** [BowlerHatLLC/vscode-as3mxml#437]
Connection refused. I'm getting

java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at com.as3mxml.vscode.Main.main(Main.java:60)

_Originally posted by @yishayw in https://github.com/BowlerHatLLC/vscode-as3mxml/issues/159#issuecomment-569396998_

**Comment by joshtynjala** [comment]
Okay, when I get a chance, I'll take a look and see if using the language server with sockets still works correctly in VSCode.
