### ISSUE TITLE
Started getting errors with new MXML files

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/vscode-as3mxml#444]
Strange new behavior since the latest update when creating new MXML files. Code completion stops working for that particular file only and I get the following error on repeat:

```
Jan 24, 2020 9:30:52 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 10
Jan 24, 2020 9:45:48 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
WARNING: Unmatched cancel notification for request id 20
Jan 24, 2020 9:46:03 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.ClassCastException: org.apache.royale.compiler.internal.tree.as.ClassNode cannot be cast to org.apache.royale.compiler.tree.metadata.IEventTagNode
java.util.concurrent.CompletionException: java.lang.ClassCastException: org.apache.royale.compiler.internal.tree.as.ClassNode cannot be cast to org.apache.royale.compiler.tree.metadata.IEventTagNode
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassCastException: org.apache.royale.compiler.internal.tree.as.ClassNode cannot be cast to org.apache.royale.compiler.tree.metadata.IEventTagNode
	at org.apache.royale.compiler.internal.definitions.EventDefinition.getNode(EventDefinition.java:47)
	at org.apache.royale.compiler.internal.definitions.EventDefinition.getNode(EventDefinition.java:37)
	at org.apache.royale.compiler.internal.definitions.DefinitionBase.getExplicitSourceComment(DefinitionBase.java:1013)
	at com.as3mxml.vscode.utils.DefinitionDocumentationUtils.getDocumentationForDefinition(DefinitionDocumentationUtils.java:39)
	at com.as3mxml.vscode.utils.CompletionItemUtils.createDefinitionItem(CompletionItemUtils.java:33)
	at com.as3mxml.vscode.providers.CompletionProvider.addEventMetadataToAutoCompleteMXML(CompletionProvider.java:1737)
	at com.as3mxml.vscode.providers.CompletionProvider.addMembersForMXMLTypeToAutoComplete(CompletionProvider.java:1529)
	at com.as3mxml.vscode.providers.CompletionProvider.mxmlCompletion(CompletionProvider.java:748)
	at com.as3mxml.vscode.providers.CompletionProvider.completion(CompletionProvider.java:202)
	at com.as3mxml.vscode.ActionScriptServices.lambda$completion$0(ActionScriptServices.java:334)
	... 6 more

[Error - 09:46:03] Request textDocument/completion failed.
  Message: Internal error.
  Code: -32603
```

This has happened a few times with new MXML file, but not always. I have been able to make it go away, but can't figure out exactly how! It's come came back again since I returned to the file in a new session. To add to the confusion, I sometimes can get code completion to suggest something (e.g. LayoutGroup), but when I select it, it's not qualified with a namespace.

**Comment by esidegallery** [comment]
I've just managed to pin it down. The error happens when the new MXML file extends an ActionScript file class that defines an [Event] metadata tag. Hope that helps!

**Comment by joshtynjala** [comment]
@esidegallery Can you try to put together some example code that reproduces the issue? I just tried some things, but unfortunately, I couldn't make it happen.

I suspect that it has to do with the placement of an `/** asdoc comment */`, but I can't quite figure out where it needs to be.

**Comment by carlosrovira** [comment]
I was thinking in creating an issue for "Create a new class file is not taken into account for as3mxml extension", but maybe could be part of this ticket (if not I can do a new one). The issue I see from many time is that creating a new class from scratch need a restart of the VSCode so AS3MXML take it into account. I think AS3MXML should know about the creation of a *.as3 or *.mxml file in a project a make it work in code intelligence. Probably extension would need to try to check until the file is correctly configured in package and name.
Thanks

**Comment by joshtynjala** [comment]
@carlosrovira Please open a new issue and include steps to reproduce. The extension definitely can handle the creation of new .as and .mxml files, so you must be hitting some weird edge case.

**Comment by esidegallery** [comment]
This issue appears to have gone away. Closing.

**Comment by varadig** [comment]
I have the same issue. What was the  solution @esidegallery ?

**Comment by esidegallery** [comment]
@varadig I honestly can't remember for sure, but I think it may have been the use of metadata tags like [Event] and using [Bindable] on getters/setters in the MXML file.
