### ISSUE TITLE
debug error when I set breakpoint

### ISSUE THREAD

**Issue by yooni126** [BowlerHatLLC/vscode-as3mxml#471]
```
error while processing request 'setBreakpoints'
java.nio.file.InvalidPathException: Illegal char <:> at index 27: AppBazaar_fla.Symbol105_423::frame1
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.as3mxml.vscode.SWFDebugSession.setBreakpoints(SWFDebugSession.java:993)
	at com.as3mxml.vscode.SWFDebugSession.setBreakpoints(SWFDebugSession.java:977)
	at com.as3mxml.vscode.debug.DebugSession.dispatchRequest(DebugSession.java:160)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.dispatch(ProtocolServer.java:143)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.processData(ProtocolServer.java:102)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.start(ProtocolServer.java:81)
	at com.as3mxml.vscode.SWFDebug.main(SWFDebug.java:49)
```
I didn't have this issue, but recenty I see this error for all of my projects !
My vscode version: 1.44.2

**Comment by joshtynjala** [comment]
Thanks! I'll get that fixed soon.
