### ISSUE TITLE
Main class not found in source paths: Main

### ISSUE THREAD

**Issue by DQvsRA** [BowlerHatLLC/vscode-as3mxml#478]
From example: https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-Adobe-AIR-for-mobile-platforms
I always get:
```
Executing task in folder Puzzlic: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java -jar /Users/vladimir.minkin/.vscode/extensions/bowlerhatllc.vscode-nextgenas-1.1.1/bin/asconfigc.jar --sdk /Users/vladimir.minkin/Documents/SDKs/AIR33 --debug=true --project /Users/vladimir.minkin/Documents/Projects/Personal/Games/Puzzlic/VSCode/asconfig.json --unpackage-anes=true --jvmargs="" <

Main class not found in source paths: Main
The terminal process terminated with exit code: 1
```

**Comment by DQvsRA** [comment]
Running project from VSCode show me different error:
```
> Executing task: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java -jar /Users/vladimir.minkin/.vscode/extensions/bowlerhatllc.vscode-nextgenas-1.1.1/bin/asconfigc.jar --sdk /Users/vladimir.minkin/Documents/SDKs/AIR33 --debug=true --project /Users/vladimir.minkin/Documents/Projects/Personal/Games/Puzzlic/VSCode/asconfig.json --unpackage-anes=true --jvmargs="" <

Error: Could not find or load main class 
The terminal process terminated with exit code: 1
```

**Comment by joshtynjala** [comment]
Can you change the `as3mxml.asconfigc.verboseOutput` setting in VSCode to `true` and try to build again? I'd like to see the more verbose output of your build. Thanks!

**Comment by DQvsRA** [comment]
Here it is with option enabled:

```
Executing task: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/bin/java -jar /Users/vladimir.minkin/.vscode/extensions/bowlerhatllc.vscode-nextgenas-1.1.1/bin/asconfigc.jar --sdk /Users/vladimir.minkin/Documents/SDKs/AIR33 --debug=true --project /Users/vladimir.minkin/Documents/Projects/Personal/Games/Puzzlic/VSCode/asconfig.json --unpackage-anes=true --verbose=true --jvmargs="" <

Configuration file: /Users/vladimir.minkin/Documents/Projects/Personal/Games/Puzzlic/VSCode/asconfig.json
Reading configuration file...
Validating configuration file...
Parsing configuration file...
SDK: /Users/vladimir.minkin/Documents/SDKs/AIR33
Compiling application...
/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/bin/java  -Dflexcompiler=/Users/vladimir.minkin/Documents/SDKs/AIR33 -Dflexlib=/Users/vladimir.minkin/Documents/SDKs/AIR33/frameworks -jar /Users/vladimir.minkin/Documents/SDKs/AIR33/lib/mxmlc-cli.jar +flexlib=/Users/vladimir.minkin/Documents/SDKs/AIR33/frameworks --debug=true +configname=airmobile --source-path+=src --output=bin/Main.swf --swf-version=44 --target-player=33.1 -- src/Main.as
Error: Could not find or load main class 
The terminal process terminated with exit code: 1
```

**Comment by joshtynjala** [comment]
What is the contents of your _src/Main.as_ file?

**Comment by joshtynjala** [comment]
> Error: Could not find or load main class 

Actually, this appears to be a Java error message when a class cannot be found in a JAR file. Something may be wrong with mxmlc-cli.jar in the AIR 33 SDK.

**Comment by DQvsRA** [comment]
> What is the contents of your _src/Main.as_ file?

It's from example:
```
package
{
	import flash.display.Sprite;
	import flash.text.TextField;

	public class Main extends Sprite
	{
		public function Main()
		{
			var tf:TextField = new TextField();
			tf.text = "Hello World";
			addChild(tf);
		}
	}
}
```

**Comment by DQvsRA** [comment]
I have tried 3 different SDKs: AIR 32, AIR+FLEX 33, AIR33

**Comment by joshtynjala** [comment]
Is your AIR SDK merged with a Flex SDK, or are you using the version of the AIR SDK that comes with its own compiler?

Does this file actually exist? /Users/vladimir.minkin/Documents/SDKs/AIR33/lib/mxmlc-cli.jar

**Comment by joshtynjala** [comment]
> Is your AIR SDK merged with a Flex SDK, or are you using the version of the AIR SDK that comes with its own compiler?

Sorry, I missed from your previous comment that you tried both.

**Comment by joshtynjala** [comment]
If you replace `"mainClass": "Main"` with this, does it make a difference?

```
"files": [
    "src/Main.as"
]
```

**Comment by DQvsRA** [comment]
> Is your AIR SDK merged with a Flex SDK, or are you using the version of the AIR SDK that comes with its own compiler?
> 
> Does this file actually exist? /Users/vladimir.minkin/Documents/SDKs/AIR33/lib/mxmlc-cli.jar

Yes, it's merged and `mxmlc-cli.jar` on it's place.

![Screenshot 2020-06-03 at 09 47 55](https://user-images.githubusercontent.com/442111/83610091-555fe900-a57f-11ea-86cb-3502100fa27f.png)

**Comment by DQvsRA** [comment]
> If you replace `"mainClass": "Main"` with this, does it make a difference?
> 
> ```
> "files": [
>     "src/Main.as"
> ]
> ```

I removed `"mainClass": "Main"` put instead what you suggested, but still have same error:
```
Configuration file: /Users/vladimir.minkin/Documents/Projects/Personal/Games/Puzzlic/VSCode/asconfig.json
Reading configuration file...
Validating configuration file...
Parsing configuration file...
SDK: /Users/vladimir.minkin/Documents/SDKs/AIR33
Compiling application...
/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/bin/java  -Dflexcompiler=/Users/vladimir.minkin/Documents/SDKs/AIR33 -Dflexlib=/Users/vladimir.minkin/Documents/SDKs/AIR33/frameworks -jar /Users/vladimir.minkin/Documents/SDKs/AIR33/lib/mxmlc-cli.jar +flexlib=/Users/vladimir.minkin/Documents/SDKs/AIR33/frameworks --debug=true +configname=airmobile --source-path+=src --output=/bin/Main.swf --swf-version=44 --target-player=33.1 -- src/Main.as
Error: Could not find or load main class 
The terminal process terminated with exit code: 1
```

**Comment by DQvsRA** [comment]
I created the same project in IDEA and this is what I have:
```
Information:[Example]: Starting Flex compiler:
"/Users/vladimir.minkin/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-2/201.7223.91/IntelliJ IDEA.app/Contents/jbr/Contents/Home/bin/java" -Dapplication.home=/Users/vladimir.minkin/Documents/SDKs/AIR -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Duser.language=en -Duser.region=en -Xmx512m -classpath "/Users/vladimir.minkin/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-2/201.7223.91/IntelliJ IDEA.app/Contents/plugins/flex/lib/idea-flex-compiler-fix.jar:/Users/vladimir.minkin/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-2/201.7223.91/IntelliJ IDEA.app/Contents/plugins/flex/lib/flex-compiler.jar:/Users/vladimir.minkin/Documents/SDKs/AIR/lib/flex-compiler-oem.jar" com.intellij.flex.compiler.FlexCompiler 57299
Information:[Example]: Compilation failed
Information:03/06/2020, 10:32 - Build completed with 3 errors and 0 warnings in 10 s 317 ms
Error:[Example]: java.net.SocketTimeoutException: Accept timed out
Error:[Example]: Exception in thread "main" 
Error:[Example]: java.lang.NoClassDefFoundError: flex2/tools/VersionInfo
	at com.intellij.flex.compiler.FlexCompiler.<clinit>(FlexCompiler.java:19)
Caused by: java.lang.ClassNotFoundException: flex2.tools.VersionInfo
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more
```

**Comment by DQvsRA** [comment]
After reinstall Flex SDK and merged with latest 33.1 Harman AIR SDK I'm able to run same code (but from different location) in IDEA.

**Comment by joshtynjala** [comment]
> Yes, it's merged and mxmlc-cli.jar on it's place.

A merged SDK should not contain mxmlc-cli.jar. This means that you merged the wrong AIR SDK with the Flex SDK. There's a special version of the AIR SDK that does not contain a compiler that's meant to be merged with the Flex SDK. On HARMAN's website, you are looking for "AIR SDK for Flex Developers" on the download page.

**Comment by DQvsRA** [comment]
Since I was able to run my code in IDEA, I will continue with this dev environment and close this issue. @joshtynjala thanks for your help and comments.
