### ISSUE TITLE
Quick Compile & Build not working with Java 1.8.0 Update 271

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/vscode-as3mxml#507]
Throws the following error:
```
java.lang.ExceptionInInitializerError
	at com.adobe.agl.impl.UPropertyAliases.<clinit>(UPropertyAliases.java:88)
	at com.adobe.agl.lang.UCharacter.<clinit>(UCharacter.java:6164)
	at com.adobe.agl.impl.Utility.unescapeAt(Utility.java:789)
	at com.adobe.agl.impl.RuleCharacterIterator.next(RuleCharacterIterator.java:164)
	at com.adobe.agl.text.UnicodeSet.applyPattern(UnicodeSet.java:2366)
	at com.adobe.agl.text.UnicodeSet.applyPattern(UnicodeSet.java:2259)
	at com.adobe.agl.text.UnicodeSet.<init>(UnicodeSet.java:366)
	at com.adobe.agl.text.DecimalFormat.<clinit>(DecimalFormat.java:1728)
	at com.adobe.fontengine.math.F16Dot16.<clinit>(Unknown Source)
	at com.adobe.fontengine.font.opentype.Glyf.createTopDict(Unknown Source)
	at com.adobe.fontengine.font.opentype.Glyf.subsetAndStreamForCFF(Unknown Source)
	at com.adobe.fontengine.font.opentype.Glyf.streamForCFF(Unknown Source)
	at com.adobe.fontengine.font.opentype.OpenTypeFont.streamSFNTForSWFEditting(Unknown Source)
	at com.adobe.fontengine.font.opentype.OTFSWFFont4Description.streamFontData(Unknown Source)
	at flash.fonts.CFFFontManager.createDefineFont4(Unknown Source)
	at flash.fonts.CFFFontManager.createDefineFont(Unknown Source)
	at flex2.compiler.media.FontTranscoder.getDefineFont(FontTranscoder.java:272)
	at flex2.compiler.media.FontTranscoder.doTranscode(FontTranscoder.java:175)
	at flex2.compiler.media.AbstractTranscoder.transcode(AbstractTranscoder.java:128)
	at flex2.compiler.as3.EmbedUtil.transcode(EmbedUtil.java:241)
	at flex2.compiler.as3.EmbedUtil.transcode(EmbedUtil.java:123)
	at flex2.compiler.as3.EmbedEvaluator.generateSources(EmbedEvaluator.java:380)
	at flex2.compiler.as3.EmbedEvaluator.generateSources(EmbedEvaluator.java:358)
	at flex2.compiler.as3.EmbedEvaluator.evaluate(EmbedEvaluator.java:107)
	at macromedia.asc.parser.ClassDefinitionNode.evaluate(ClassDefinitionNode.java:106)
	at flash.swf.tools.as3.EvaluatorAdapter.evaluate(EvaluatorAdapter.java:359)
	at macromedia.asc.parser.StatementListNode.evaluate(StatementListNode.java:60)
	at flash.swf.tools.as3.EvaluatorAdapter.evaluate(EvaluatorAdapter.java:944)
	at flex2.compiler.as3.EmbedEvaluator.evaluate(EmbedEvaluator.java:340)
	at macromedia.asc.parser.ProgramNode.evaluate(ProgramNode.java:80)
	at flex2.compiler.as3.EmbedExtension.parse2(EmbedExtension.java:78)
	at flex2.compiler.as3.As3Compiler.parse2(As3Compiler.java:468)
	at flex2.compiler.CompilerAPI.parse2(CompilerAPI.java:2954)
	at flex2.compiler.CompilerAPI.parse2(CompilerAPI.java:2911)
	at flex2.compiler.CompilerAPI.batch2(CompilerAPI.java:477)
	at flex2.compiler.CompilerAPI.batch(CompilerAPI.java:1297)
	at flex2.compiler.CompilerAPI.compile(CompilerAPI.java:1528)
	at flex2.tools.Fcsh.mxmlc(Fcsh.java:993)
	at flex2.tools.Fcsh.process(Fcsh.java:149)
	at flex2.tools.Fcsh.main(Fcsh.java:86)
Caused by: java.lang.IllegalArgumentException: Invalid version number: Version number may be negative or greater than 255
	at com.adobe.agl.util.VersionInfo.getInstance(VersionInfo.java:191)
	at com.adobe.agl.impl.ICUDebug.getInstanceLenient(ICUDebug.java:65)
	at com.adobe.agl.impl.ICUDebug.<clinit>(ICUDebug.java:69)
	... 40 more
```

**Comment by joshtynjala** [comment]
Based on the stack trace, the Flex compiler seems to be having trouble transcoding an embedded OTF font file.

I suspect that there's not much that I will be able to do on my end. I'm just passing commands to the Flex compiler shell (FCSH).
