### ISSUE TITLE
AcitonScript/MXML Server got closed!

### ISSUE THREAD

**Issue by huybui38** [BowlerHatLLC/vscode-as3mxml#536]
Here is the extension output:
`[Error - 7:29:54 PM] Request textDocument/codeAction failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:248534)
    at Object.dispose (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:142861)
    at x.handleConnectionClosed (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:143036)
    at x.handleConnectionClosed (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:163874)
    at t (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:141183)
    at n.invoke (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:232974)
    at i.fire (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:233704)
    at $ (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:240347)
    at n.invoke (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:232974)
    at i.fire (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:233704)
    at l.fireClose (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:251528)
    at Socket.<anonymous> (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:252290)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)
[Error - 7:29:54 PM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:248534)
    at Object.dispose (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:142861)
    at x.handleConnectionClosed (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:143036)
    at x.handleConnectionClosed (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:163874)
    at t (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:141183)
    at n.invoke (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:232974)
    at i.fire (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:233704)
    at $ (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:240347)
    at n.invoke (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:232974)
    at i.fire (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:233704)
    at l.fireClose (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:251528)
    at Socket.<anonymous> (c:\Users\NgocHuy\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\extension.js:1:252290)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:673:12)`

**Comment by joshtynjala** [comment]
Did you happen to force quit any Java processes? It looks like some of the Java code has quit without notifying the extension. Anyway, if this happens again, you should restart VSCode.
