### ISSUE TITLE
Debugger error when adding breakpoints to SWC component

### ISSUE THREAD

**Issue by wmfelipe** [BowlerHatLLC/vscode-as3mxml#539]
Hi, @joshtynjala 
first of all, thanks for this great extension. I'm trying to use it but I'm facing some issues when I run the project to debug. I've read all created issues in your repo but I've found no solution that works in my case.

So, I have 3 root folders in my saved workspace:
- A project with components that builds a SWC file.
- A Flex project that uses the SWC component and builds a SWF file.
- And an Air desktop project that also uses the SWC components, but when this Air project runs it just loads the Flex SWF file (I mentioned at previous item) from an external host (this.ByteLoader.load(new URLRequest("http://localhost/myFlex.swf"))).

I know it may seems an unusual structure, but it's a legacy project and it runs fine on Eclipse/Flash Builder.

I already be able to make those 3 builds (compile debug mode) and run the Air project by your extension, but when I try to create a breakpoint in the Flex or SWC project, the follow error appears:

```
Exception in debugger: flash.tools.debugger.InProgressException
	at flash.tools.debugger.concrete.DSwfInfo.swdLoaded(DSwfInfo.java:162)
	at flash.tools.debugger.concrete.DSwfInfo.getSourceList(DSwfInfo.java:137)
	at flash.tools.debugger.threadsafe.ThreadSafeSwfInfo.getSourceList(ThreadSafeSwfInfo.java:84)
	at com.as3mxml.vscode.SWFDebugSession.setBreakpoints(SWFDebugSession.java:1012)
	at com.as3mxml.vscode.SWFDebugSession.setBreakpoints(SWFDebugSession.java:996)
	at com.as3mxml.vscode.debug.DebugSession.dispatchRequest(DebugSession.java:160)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.dispatch(ProtocolServer.java:143)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.processData(ProtocolServer.java:102)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.start(ProtocolServer.java:81)
	at com.as3mxml.vscode.SWFDebug.main(SWFDebug.java:49)
```
	
The breakpoints just work if they were created in Air project (the only that has de launch.json configured).

Please, could you help me to find out how to solve this?

Thanks in advance.

**Comment by joshtynjala** [comment]
@wmfelipe Have you noticed that the breakpoints in the Flex/SWC project actually work correctly, even though you see the exception message?

Based on some digging, an `InProgressException` simply means that some of the debugging data hasn't finished loading yet, and the solution is to save the breakpoints and try to add them again later. As best I can tell, that's actually what vscode-swf-debug is doing already. The only issue seems to be that it is printing the **caught** exception message when that information isn't relevant to you, the user.

If you haven't tried yet, please check to see if the breakpoints might be working properly. Thanks!

**Comment by wmfelipe** [comment]
Hi @joshtynjala 
the breakpoint doesn't work. I've run the project, and after the project was loaded I've waited a few minutes before create the breakpoint, but it always turns grey, shows a tooltip "Unverified Breakpoint" and doesn't work, even if I create the breakpoint before or after run the project.

I've also created a launch.json file in Flex project, but I've saw no difference when I run the main Air project.

Thanks!

**Comment by joshtynjala** [comment]
@wmfelipe When you are compiling each of your projects, are you compiling debug or release? You need to compile debug because if you compile release, the .swc and .swf files won't have enough information for the debugger. That could potentially explain why the debugger is not completing its load of debug data.

**Comment by wmfelipe** [comment]
Hi @joshtynjala 
yes, when I compile the projects I always use the "compile debug" option, and if I run by Eclipse these same compiled files, the breakpoints work fine.

I'm also using the option "debug": true in compilerOptions.

Thanks!

**Comment by wmfelipe** [comment]
@joshtynjala 
but there is a curious thing..
In SWC project, the compile debug build only works if I use "config": "air" in asconfig.json file.

Below are my config files:

**asconfig.json (SWC project) (Components)**
`{
    "config": "air",
    "type": "lib",
	"copySourcePathAssets": true,
    "compilerOptions": {
        "output": "bin\\Components.swc",
        "include-classes": [
            "com.GlobalFunctions",
            "com.iberia.GlobalVars",
            A LOT OF ITEMS....
            "org.idmedia.as3commons.util.StringUtils",
            "com.mycomponents.LgApp_edit_panels.popup_BlankFooter"
        ],
        "library-path": [
            "libs",
            "C:\\xampp\\htdocs\\RTDTESTING4TOIGA\\NavBar.swc"
        ],
        "source-path": [
            "C:\\Users\\Felipe\\Documents\\PROJETOS\\cube_framework_components\\src"
        ],
        "theme": "C:\\APACHE\\halo.swc",
        "debug": true,
		"warnings": false
    }
}`

**asconfig.json (Flex project) (Loaded by HTTP**)
`{
    "config": "flex",
    "mainClass": "iBeriaMaster",
    "copySourcePathAssets": true,
    "keep-generated-actionscript": true,
    "compilerOptions": {
        "output": "C:\\xampp\\htdocs\\RTDTESTING4TOIGA\\fw\\iBeriaMaster.swf",
        "strict": false,
		"library-path": [
            "C:\\Users\\Felipe Busanello\\Documents\\PROJETOS\\cube_framework_components\\bin\\Components.swc",
            "C:\\xampp\\htdocs\\RTDTESTING4TOIGA\\NavBar.swc"
        ],
        "source-path": [
            "C:\\Users\\Felipe Busanello\\Documents\\PROJETOS\\cube_framework_flex_iberiaMaster\\src"
        ],
        "static-link-runtime-shared-libraries": true,
        "theme": "C:\\APACHE\\halo.swc",
        "debug": true,
        "warnings": false
	}
}`

**asconfig.json (Air project) (Main)**
`{
    "config": "air",
    "mainClass": "cube",
    "application": "src/cube-app.xml",
    "copySourcePathAssets": true,
    "keep-generated-actionscript": true,
	"compilerOptions": {
		"source-path": [
            "C:\\Users\\Felipe\\Documents\\PROJETOS\\cube_framework_cube_air\\src"
        ],
		"output": "C:\\APACHE\\htdocs\\Cube\\bin-debug\\cube.swf",
        "library-path": [
            "libs",
            "C:\\Users\\Felipe\\Documents\\PROJETOS\\cube_framework_components\\bin\\Components.swc",
            "C:\\xampp\\htdocs\\RTDTESTING4TOIGA\\NavBar.swc"
        ],
        "theme": "C:\\APACHE\\halo.swc",
        "static-link-runtime-shared-libraries": true,
        "debug": true,
        "warnings": false
	},
    "additionalOptions": "-locale en_US -includes=mx.managers.systemClasses.MarshallingSupport"
}`

**Comment by joshtynjala** [comment]
> but there is a curious thing..
> In SWC project, the compile debug build only works if I use "config": "air" in asconfig.json file.

What happens when you don't use `"config": "air"` in your _asconfig.json_ file? Do you get compilation errors? If you get errors, I would assume that it's because your SWF project is using classes that are available in AIR, but not available in Flash Player.

**Comment by wmfelipe** [comment]
@joshtynjala 
If I don't set the "config" option I get some errors:

```
> Executing task in folder cube_framework_components: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe -jar c:\Users\Felipe\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\bin\asconfigc.jar --sdk c:\Program Files (x86)\Adobe\Adobe Flash Builder 4 Plug-in\sdks\3.5.0 --clean=true --project c:\Users\Felipe\Documents\PROJETOS\cube_framework_components\asconfig.json <


Terminal will be reused by tasks, press any key to close it.

> Executing task in folder cube_framework_components: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe -jar c:\Users\Felipe\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\bin\asconfigc.jar --sdk c:\Program Files (x86)\Adobe\Adobe Flash Builder 4 Plug-in\sdks\3.5.0 --debug=true --project c:\Users\Felipe\Documents\PROJETOS\cube_framework_components\asconfig.json <

Loading configuration file C:\Program Files (x86)\Adobe\Adobe Flash Builder 4 Plug-in\sdks\3.5.0\frameworks\flex-config.xml
C:\Users\Felipe\Documents\PROJETOS\cube_framework_components\src\com\mycomponents\ibTracker\ibTracker.as(354): col: 9 Error: Chamar um método possivelmente indefinido save por meio de uma referência com tipo estático flash.net:FileReference.

                        file.save(xml,"report.xml");
                             ^
....
MUCH MORE ERRORS HERE........
......

C:\Users\Felipe\Documents\PROJETOS\cube_framework_components\src\com\mycomponents\lgapp_as\lgapp_fw_EditMode.as(21239): col: 115 Error: Acesso de propriedade possivelmente indefinida data por meio de uma referência com tipo estático flash.net:FileReference.

        link += "?imgName=" + url_info['first_folder'] + "/docs/ibApp/" + this.fileRef.name + "&tamanho=" + this.fileRef.data.bytesAvailable;
                           this.dg_events.dispatchEvent(new Event(Event.PASTE));

C:\Users\Felipe\Documents\PROJETOS\cube_framework_components\src\com\mycomponents\LgApp_edit_panels\popup_LgApp_properties_panel.mxml(17979):  Error: Acesso de propriedade possivelmente indefinida PASTE por meio de uma referência com tipo estático Class.

                                                this.dg_events.removeEventListener(Event.PASTE, this.lg_internal_br_clipboard_context_menu_paste_action);

The terminal process "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe '-jar', 'c:\Users\Felipe\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.7.1\bin\asconfigc.jar', '--sdk', 'c:\Program Files (x86)\Adobe\Adobe Flash Builder 4 Plug-in\sdks\3.5.0', '--debug=true', '--project', 'c:\Users\Felipe\Documents\PROJETOS\cube_framework_components\asconfig.json'" terminated with exit code: 44.

Terminal will be reused by tasks, press any key to close it.
```

**Comment by joshtynjala** [comment]
> C:\Program Files (x86)\Adobe\Adobe Flash Builder 4 Plug-in\sdks\3.5.0

It looks like your using Adobe Flex SDK 3.5.0, which targeted Flash Player 9 by default.

> col: 9 Error: Chamar um método possivelmente indefinido save por meio de uma referência com tipo estático flash.net:FileReference.
>                        file.save(xml,"report.xml");


> Error: Acesso de propriedade possivelmente indefinida PASTE por meio de uma referência com tipo estático Class.
>                                                 this.dg_events.removeEventListener(Event.PASTE, this.lg_internal_br_clipboard_context_menu_paste_action);

According to the documentation, FileReference.save and Event.PASTE were added in Flash Player 10, so the default _playerglobal.swc_ file for Flex 3.5.0 would not have them.

I assume that you've merged Flex 3.5.0 with a more recent version the AIR SDKt. When you use `"config": "air"`, it tells the compiler to use _airglobal.swc_ instead of _playerglobal.swc_, and it gives you access to more APIs. Your AIR SDK's _airglobal.swc_ file is probably what defines FileReference.save and Event.PASTE.

If you wanted to remove `"config": "air"` from your _asconfig.json_, for some reason, you may be able replace _playerglobal.swc_ in your Flex 3.5.0 SDK with a newer version.

Adobe has version 32.0 available from this page, for instance:

https://www.adobe.com/support/flashplayer/debug_downloads.html

**Comment by wmfelipe** [comment]
Hi @joshtynjala 
I've configured in VSCode those same SDKs that I have in Eclipse. The SWC project uses DSK v3.5 and the Flex and Air projects use Flex Hero v4.5. And the flash player I've installed is 32.

Is it wrong if I use "config: air" to build the SWC?
When I get all builds made by VSCode and run the Air project by Eclipse the breakpoints work. So, for me it seems the builds are ok, but I'm not shure.

Thanks again!

**Comment by joshtynjala** [comment]
> Is it wrong if I use "config: air" to build the SWC?

No, it is not wrong. If someone need to use any APIs that are in AIR, but not Flash Player, then `"config: air"` is required. To be clear, `"config: air"` is not for application projects only. It may be used in both library and application projects, when you are targeting AIR.

In your Eclipse project, you probably have the check box to include AIR classes selected, so this would be exactly the same.

**Comment by joshtynjala** [comment]
To also be clear, the breakpoints issue has nothing to do with `"config: air"`. It's a bug in vscode-swf-debug. I can fix it, if I can find a way to reproduce it on my computer. One way to help me reproduce would be to create a simplified set of projects where you can see the whole problem. Either by creating new projects with the bare minimum code required, or by removing as much as possible from your existing projects (including anything that you wouldn't want to share publicly).
