### ISSUE TITLE
Symbol Renaming Error

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#659]
When I rename a symbol, sometimes it works, and sometimes doesn't.
For example, the same symbol, worked at the first time, error at the second time of renaming.
The output:

```
[Error - 11:52:35 AM] Request textDocument/rename failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at org.apache.royale.compiler.common.DependencyTypeSet.add(DependencyTypeSet.java:207)
	at org.apache.royale.compiler.internal.projects.DependencyGraph$Edge.addDependency(DependencyGraph.java:228)
	at org.apache.royale.compiler.internal.projects.DependencyGraph$Edge.access$200(DependencyGraph.java:129)
	at org.apache.royale.compiler.internal.projects.DependencyGraph.addDependency(DependencyGraph.java:384)
	at org.apache.royale.compiler.internal.projects.CompilerProject.addDependency(CompilerProject.java:590)
	at org.apache.royale.compiler.internal.scopes.ASScopeCache.findProperty(ASScopeCache.java:156)
	at org.apache.royale.compiler.internal.scopes.ASScope.findProperty(ASScope.java:1468)
	at org.apache.royale.compiler.internal.tree.as.IdentifierNode.resolve(IdentifierNode.java:383)
	at com.as3mxml.vscode.utils.ASTUtils.findIdentifiersForDefinition(ASTUtils.java:442)
	at com.as3mxml.vscode.utils.ASTUtils.findIdentifiersForDefinition(ASTUtils.java:484)
	at com.as3mxml.vscode.utils.ASTUtils.findIdentifiersForDefinition(ASTUtils.java:484)
	at com.as3mxml.vscode.utils.ASTUtils.findIdentifiersForDefinition(ASTUtils.java:484)
	at com.as3mxml.vscode.utils.ASTUtils.findIdentifiersForDefinition(ASTUtils.java:484)
	at com.as3mxml.vscode.providers.RenameProvider.renameDefinition(RenameProvider.java:308)
	at com.as3mxml.vscode.providers.RenameProvider.actionScriptRename(RenameProvider.java:172)
	at com.as3mxml.vscode.providers.RenameProvider.rename(RenameProvider.java:143)
	at com.as3mxml.vscode.ActionScriptServices.rename2(ActionScriptServices.java:770)
	at com.as3mxml.vscode.ActionScriptServices.lambda$rename$13(ActionScriptServices.java:756)
	... 6 more
```

**Comment by ylazy** [comment]
This issue still exist in As3MXML v1.16.0:

https://user-images.githubusercontent.com/6010183/233534349-97bb9247-6ca0-4200-84ee-cb4e440bf738.mp4

**Comment by joshtynjala** [comment]
I expect that apache/royale-compiler@a3dd80ca8bc0ed4a62e9abd2825f65ae242e1418 will help with this issue. However, we'll need to wait for it to be included in a Royale release.
