### ISSUE TITLE
error while processing request 'evaluate'

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#694]
This error occured during my debugging:

![image](https://github.com/BowlerHatLLC/vscode-as3mxml/assets/6010183/2c6d44c9-a390-44f3-a6f3-08a0c731a237)

```
error while processing request 'evaluate'
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.apache.royale.utils.CheapArray.get(CheapArray.java:133)
	at org.apache.royale.compiler.internal.tree.as.TreeNode.getChild(TreeNode.java:67)
	at flash.tools.debugger.expression.DebuggerUtil.parseExpression(DebuggerUtil.java:71)
	at flash.tools.debugger.expression.ASTBuilder.parse(ASTBuilder.java:136)
	at com.as3mxml.vscode.SWFDebugSession.evaluate(SWFDebugSession.java:1960)
	at com.as3mxml.vscode.debug.DebugSession.dispatchRequest(DebugSession.java:168)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.dispatch(ProtocolServer.java:143)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.processData(ProtocolServer.java:102)
	at com.as3mxml.vscode.debug.protocol.ProtocolServer.start(ProtocolServer.java:81)
	at com.as3mxml.vscode.SWFDebug.main(SWFDebug.java:49)

```

**Comment by joshtynjala** [comment]
I can reproduce this issue. It is technically a bug in the Royale debugger, but I think I can work around it in vscode-swf-debug too, until the next Royale release.

It can be reproduced by hovering your mouse over certain AS3 keywords, like `switch`, while the debugger is stopped at a breakpoint.
